apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ceph-object-user.yaml
  - config.yaml
  - bucket-job.yaml
  - cnpg.yaml
  - backend.yaml
  - dashboard.yaml
  - ingress.yaml
  - cilium-network-policy.yaml
